### ISSUE TITLE
Specify a unique webroot for each domain set

### ISSUE THREAD

**Issue by hackel** [saltstack-formulas/letsencrypt-formula#28]
There should be a way to specify a separate webroot for each domain set.  Something like this:
```yml
domainsets:
  www:
    domains:
      - example.com
      - www.example.com
    webroot: /var/www/domain.com/public
  mail:
    domains:
      - imap.example.com
      - smtp.example.com
      - mail.example.com
    webroot: /var/www/mail/public
  intranet:
    domains:
      - intranet.example.com
    webroot: /var/www/intranet/public
```

I solved this by picking one real webroot and symlinking the others to it, but I dislike this manual step.
