### ISSUE TITLE
Warnings due to file.absent with excessive flags

### ISSUE THREAD

**Issue by dehnert** [saltstack-formulas/letsencrypt-formula#64]
When I use this formula, I get the following warnings:
```
----------
          ID: /usr/bin/certbot renew --dry-run --cert-name
    Function: file.absent
      Result: True
     Comment: File /usr/bin/certbot renew --dry-run --cert-name is not present
     Started: 07:10:06.754729
    Duration: 3.858 ms
     Changes:   
    Warnings: 'source', 'mode' and 'template' are invalid keyword arguments for
              'file.absent'. If you were trying to pass additional data to be
              used in a template context, please populate 'context' with 'key:
              value' pairs. Your approach will work until Salt Nitrogen is out.
              Please update your state files.
----------
          ID: /usr/bin/certbot renew
    Function: file.absent
      Result: True
     Comment: File /usr/bin/certbot renew is not present
     Started: 07:10:06.770253
    Duration: 3.709 ms
     Changes:   
    Warnings: 'source', 'mode' and 'template' are invalid keyword arguments for
              'file.absent'. If you were trying to pass additional data to be
              used in a template context, please populate 'context' with 'key:
              value' pairs. Your approach will work until Salt Nitrogen is out.
              Please update your state files.
```

Presumably, those parameters should be conditioned on use_package being false.

**Comment by grandmasterv** [comment]
I'm also confused as to why the formula is even creating states using a cmd for a file path.  It looks like to me that these states will never work.  What are these states supposed to be accomplishing?

```
/usr/bin/certbot renew --dry-run --cert-name:
  file.absent:
    - template: jinja
    - source: salt://letsencrypt/files/check_letsencrypt_cert.sh.jinja
    - mode: 755

/usr/bin/certbot renew:
  file.absent:
    - template: jinja
    - source: salt://letsencrypt/files/renew_letsencrypt_cert.sh.jinja
    - mode: 755
    - require:
      - file: /usr/bin/certbot renew --dry-run --cert-name
```
