### ISSUE TITLE
Wildcard Support?

### ISSUE THREAD

**Issue by hyphus** [saltstack-formulas/letsencrypt-formula#68]
Does this formula support wildcard certificates?

Looking through the pillar example it doesn't appear to but I wanted to confirm.

**Comment by javierbertoli** [comment]
yes. This configuration should let you obtain a wildcard

```yaml
letsencrypt:
  use_package: true
  pkgs:
    - python3-certbot-dns-route53
  config:
    agree-tos: true
    keep-until-expiring: true
    expand: true
    max-log-backups: 0
    authenticator: dns-route53
  domainsets:
    - "*.some.domain"
```
Or any other authenticator plugin you need to use (dns-cloudflare, etc) for DNS01 challenges. Make sure to check each plugin configuration, as it differs and might require you set extra resources, like credentials files.

Once #83 is merged, it will be possible to set these parameters for each domainset individually.
