### ISSUE TITLE
[BUG]  Installing on CentOS7 minion

### ISSUE THREAD

**Issue by mturra-Pro** [saltstack-formulas/letsencrypt-formula#78]
### Formula commit hash / release tag

90d8a069b64ded15a5299a0980705cc37a42c069

### Versions reports (master & minion)

Salt Version:
           Salt: 3001.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 4.0.1
      gitpython: 3.0.9
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: 3.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.28.1.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core

### Pillar / config used

```
letsencrypt:
  domainsets:
    www:
      - example.com
  post_renew:
    cmds:
      - service httpd reload
```

---

### Describe the bug

In installed epel repo as described in Readme.md

### Steps to reproduce the bug

salt -l debug my-minion state.apply letsencrypt

```
          ID: letsencrypt-client
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
     Started: 16:43:35.448172
    Duration: 12855.414 ms
```

### Expected behaviour

Correct installation
