### ISSUE TITLE
Initial lack of cert is not handled correctly

### ISSUE THREAD

**Issue by gravyboat** [saltstack-formulas/letsencrypt-formula#9]
I ran into this while configuring a new server with a new domain earlier this week. The problem is if you use something like the nginx formula which serves up your custom nginx conf there's no way to avoid errors with the attempted redirect prior to the cert generation. I believe this issue is definitely related more closely to the nginx/apache formulas, but that we may wish to solve it here for initial certificate generation. This is by no means perfect, but it would allow users to do a top that looks something like:

```
base:
  '*':
    - letsencrypt.nginx
    - letsencrypt
    - letsencrypt.nginx-clean
    - nginx.blahblahblah
```

We would create a default site with the nginx config file inside of letsencrypt.nginx so the site is responsive pulling from the variables, do the letsencrypt work, then clean up the config and the associated dirs. This would also avoid conflicts between named nginx configs.

@martinhoefling Any thoughts or opinions on this? How are you working around this? Right now I have to drop on my salt config, let it bomb, modify the conf, then run salt again so letsencrypt finishes before the nginx component runs and everything works, definitely not ideal.

**Comment by martinhoefling** [comment]
So what I am doing is the following:

Every domain in my nginx config includes something like this:

```
location '/.well-known/acme-challenge' {
    default_type "text/plain";
    root /var/letsencrypt-acme-challenge;
}
```

then I configure letsencrypt to use that path to serve the challenge responses:

```
webroot-path = /var/letsencrypt-acme-challenge/
```

I never remove the .well-known path since there is no secret information in there, and I make sure that webserver is reconfigured before letsencrypt state.

In the suggested letsencrypt.nginx and letsencrypt.nginx-clean states, is there the entire nginx reconfigured or just the .well-known challenge path? I have no strong opinion on how to solve this - I would just prefer not to couple it too strongly to the actual letsencrypt set-up since this can be mostly independent (i.e. when you configure certs for a mail server).

**Comment by gravyboat** [comment]
It would use the exact same challenge path, the only thing that it does is create an http ONLY nginx config so that letsencrypt can actually auth against the cert, instead of hitting the standard 301 https redirect that is used a lot.

**Comment by martinhoefling** [comment]
Ah ok, wasn't clear to me that you're redirecting to https. So you can still handle `.well-known/acme-challenge` differently from the 301 right? I do not get what the nginx-clean step is good for.

**Comment by gravyboat** [comment]
You can't handle the acme-challenge if the 301 redirect exists before the cert exists (the https request will fail). The nginx-clean step deletes the confs associated with the site so that the real confs can be dropped in by the nginx formula.

**Comment by martinhoefling** [comment]
Hmm, I have no clear idea how to solve this issue within the letsencrypt formula. I would probably just go for some nginx/apache config that returns 301(on http) for all urls except the acme challenge dir.

**Comment by harleyg321** [comment]
I've just come across this issue while putting together my own formula and found this issue while looking for solutions.

I ended up having a state which sets a default server block that serves up `.well-known/acme-challenge` requests. At this point you wouldn't have a block for the domain you need a certificate for so it would just match the default block, and nginx will be able to start.

After certificates have been created then you can add the rest of the server blocks as normal. If each server block has the acme-challenge location then renewals for existing domains will still work. As long as these states require the create-initial-cert state then they won't be run until the relevant certificates have been created.

I was able to get a site running with no clean up required of intermediary confs, or any nginx errors from missing certificates.

**Comment by gravyboat** [comment]
@harleyg321 Yeah this is also what I did, and pretty much what I'm proposing with this issue, just the fully automated process to handle that functionality.

**Comment by blarghmatey** [comment]
So, the workaround that I came up with is to use a conditional in my pillar data for Nginx. It means that I have to run the Nginx state twice to update the config after cert generation, but it doesn't result in an Nginx instance that is unable to start without manual intervention.

```
nginx:
  ng:
    vhosts:
      managed:
        elasticsearch:
          enabled: True
          config:
            - server:
                - server_name: my.domain.com
                - listen:
                    - 80
                - listen:
                    - '[::]:80'
                - location /:
                    - proxy_pass: http://localhost:9200$uri
                    - proxy_set_header: 'X-Forwarded-For $proxy_add_x_forwarded_for'
                - location /.well-known:
                    - alias: /var/www/.well-known/
                - location /nginx_status:
                    - stub_status: 'on'
                    - allow: 127.0.0.1
                    - deny: all
                {% if salt.file.directory_exists('/etc/letsencrypt/live/my.domain.com/') %}
                - listen:
                    - 443
                    - ssl
                - listen:
                    - '[::]:443'
                    - ssl
                - 'if ($scheme != "https")':
                    - return: 301 https://$host$request_uri
                - ssl_certificate: /etc/letsencrypt/live/my.domain.com/fullchain.pem
                - ssl_certificate_key: /etc/letsencrypt/live/my.domain.com/privkey.pem
                - ssl_trusted_certificate: /etc/letsencrypt/live/my.domain.com/chain.pem
                - ssl_stapling: 'on'
                - ssl_stapling_verify: 'on'
                - ssl_session_timeout: 1d
                - ssl_session_tickets: 'off'
                - ssl_protocols:
                    - TLSv1.2
                - ssl_ciphers: 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS'
                - ssl_prefer_server_ciphers: 'on'
                - resolver: 8.8.8.8
                {% endif %}
```
